---
version: "2"
services:
    www:
        build: .
        ports:
            - "80:80"
        volumes:
            - ./web:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:5.7.28
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: leehoang
            MYSQL_USER: leehoang
            MYSQL_PASSWORD: 123
            MYSQL_ROOT_PASSWORD: 123
        volumes:
            - ./data:/docker-entrypoint-initdb.d
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - 82:80
        environment:
            MYSQL_USER: leehoang
            MYSQL_PASSWORD: 123
            MYSQL_ROOT_PASSWORD: 123
volumes:
    persistent:
